"""Comments updated #2

Revision ID: b15143695ffb
Revises: bcc659a0692c
Create Date: 2024-10-17 22:31:19.494558

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b15143695ffb'
down_revision: Union[str, None] = 'bcc659a0692c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('is_banned', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'is_banned')
    # ### end Alembic commands ###
