"""User model. banned renamed into is_banned

Revision ID: 6d7988ca6d53
Revises: 13c9035bfa84
Create Date: 2024-10-17 17:47:22.611042

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d7988ca6d53'
down_revision: Union[str, None] = '13c9035bfa84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_banned', sa.Boolean(), nullable=False))
    op.drop_column('users', 'banned')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('banned', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('users', 'is_banned')
    # ### end Alembic commands ###
