"""Comments banned_at added

Revision ID: 06a706fd27a4
Revises: b15143695ffb
Create Date: 2024-10-18 13:18:38.579710

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06a706fd27a4'
down_revision: Union[str, None] = 'b15143695ffb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('banned_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'banned_at')
    # ### end Alembic commands ###
